export const CalendarLocators = {
    listingRow: (listingId) => `tr:has([qa-id*="${listingId}"])`,
    listingCheckbox: (listingId) => `[qa-id="bulk-${listingId}___vrm"]`,
    dsoStatusBand: (listingId) => `[qa-id="dso-band-text-${listingId}"]`,
    saveRefreshBtn: (listingId) => `[qa-id="save-${listingId}___vrm"]`,
    listingIdText: (id) => `.pd-copy-listing-id`,
    syncToggle: (id) => `[qa-id="mc-sync-toggle-${id}"]`,
    listingEllipses: (id) => `[qa-id="listing-ellipses-${id}"]`,
    viewOverridesOption: (id) => `[qa-id="dso-view-${id}"]`,
    pricingBadge: (listingId, index) => `[qa-id="price-tooltip--${listingId}-${index}"]`,
    calendarHeaderDate: (date) => `div[qa-id="calendar-header-${date}"]`,
    basePriceInput: (id) => `[qa-id="base-price-${id}___vrm"]`,
    editOverrideBtn: (date) => `[qa-id="edit-override-view-${date}"]`,
    deleteOverrideBtn: (date) => `[qa-id="delete-override-view-${date}"]`,
    overrideRowByDate: (dateText) => `tr:contains("${dateText}")`,
    editOverrideBtn: (date) => `[qa-id="edit-override-view-${date}"]`,

    searchListingInput: '[qa-id="search-input"]',
    propertyName: '.chakra-text.css-1kh6bo9',
    modalTitle: '[qa-id="dso-modal-title"]',
    priceInput: '[qa-id="dso-price"]',
    addDsoButton: '[qa-id="add-dso-button"]',
    updateDsoButton: '[qa-id="update-dso"]',
    autoRefreshLoader: '.dso-auto-refresh-loader',
    progressBar: '[role="progressbar"]',
    priceError: '[qa-id="dso-price-error"]',
    viewModalTitle: '[qa-id="dso-view-modal-title"]',
    noDsoMessage: '[qa-id="no-dso"]',
    viewModalCloseBtn: '[qa-id="dso-view-modal-close-button"]',
    autoRefreshLoader: '.dso-auto-refresh-loader',
    modalTitle: '[qa-id="dso-modal-title"]'
};