export const CalendarLocators = {
    listingRow: (listingId) => `tr:has([qa-id*="${listingId}"])`,
    listingRow: (id) => `tr:has([qa-id*="${id}"])`,
    listingCheckbox: (listingId) => `[qa-id="bulk-${listingId}___vrm"]`,
    dsoStatusBand: (listingId) => `[qa-id="dso-band-text-${listingId}"]`,
    saveRefreshBtn: (listingId) => `[qa-id="save-${listingId}___vrm"]`,
    listingIdText: (id) => `.pd-copy-listing-id`,
    syncToggle: (id) => `[qa-id="mc-sync-toggle-${id}"]`,
    listingEllipses: (id) => `[qa-id="listing-ellipses-${id}"]`,
    viewOverridesOption: (id) => `[qa-id="dso-view-${id}"]`,
    calendarHeaderDate: (date) => `div[qa-id="calendar-header-${date}"]`,
    basePriceInput: (id) => `[qa-id="base-price-${id}___vrm"]`,
    deleteOverrideBtn: (date) => `[qa-id="delete-override-view-${date}"]`,
    overrideRowByDate: (dateText) => `tr:contains("${dateText}")`,
    editOverrideBtn: (date) => `[qa-id="edit-override-view-${date}"]`,
    listingBasePriceInput: (id) => `[qa-id="base-price-${id}___vrm"]`, // Function
    pricingCell: (listingId, index) => `td:has([qa-id="price-tooltip--${listingId}-${index}"])`,
    dsoBandBadge: (id) => `[qa-id="mc-dso-band-${id}"]`,
    pricingBadge: (listingId, index) => `[qa-id="price-tooltip--${listingId}-${index}"]`,

    searchListingInput: '[qa-id="search-input"]',
    propertyName: '.chakra-text.css-1kh6bo9',
    updateDsoButton: '[qa-id="update-dso"]',
    progressBar: '[role="progressbar"]',
    viewModalTitle: '[qa-id="dso-view-modal-title"]',
    noDsoMessage: '[qa-id="no-dso"]',
    viewModalCloseBtn: '[qa-id="dso-view-modal-close-button"]',
    autoRefreshLoader: '.dso-auto-refresh-loader',
    modalTitle: '[qa-id="dso-modal-title"]',
    errorToast: '#chakra-toast-manager-top-left',
    warningGoBackBtn: '[qa-id="dso-override-confirmation-go-back-button"]',
    addDsoButton: '[qa-id="add-dso-button"]',
    priceInput: '[qa-id="dso-price"]',
    priceError: '[qa-id="dso-price-error"]',
    warningModalTitle: '[qa-id="dso-warning-modal-title"]',
    warningGoBackBtn: '#bulk-dso-confirmation-go-back-button',
    errorToast: '.chakra-toast [data-status="error"]',
    toastDescription: '.chakra-alert__desc',
    modalAddMinBtn: '[qa-id="dso-min-price-label"] + button',
    modalAddMaxBtn: '[qa-id="dso-max-price-label"] + button',
    modalMinPriceLabel: '[qa-id="dso-min-price-label"]',
    modalMaxPriceLabel: '[qa-id="dso-max-price-label"]',
    modalAddBaseBtn: '[qa-id="add-base-price-btn"]',
    modalGenericAddBtn: '[qa-id="add-value-btn"]',
    modalBasePriceInput: '[qa-id="dso-base-price"]',
    modalMinPriceInput: '[qa-id="dso-min-price"]',
    modalMaxPriceInput: '[qa-id="dso-max-price"]',
    modalOverridePriceInput: '[qa-id="dso-price"]',
    adrValue: '.css-za9x12 p.css-hbdr6j',
    totalValue: '.css-1igwmid p.css-hbdr6j',
    tooltipContainer: '[role="tooltip"]',
    summaryPopover: '[id^="popover-content-"]', 
    modalTitle: '[qa-id="dso-modal-title"]',
    notificationCloseBtn: '[qa-id="undefined-close-btn"]',
    chakraAlert: '.chakra-alert',
    warningModalTitle: '[qa-id="dso-warning-modal-title"]',
    warningModalFooter: '.chakra-modal__footer',
    confirmUpdateButton: '[qa-id="dso-override-confirmation-update-button"]',
    dsoBadge: '.mc-dso-band', 
    autoRefreshLoader: '.dso-auto-refresh-loader',
};